---
title: "region_card text"
author: "Camila Vargas"
date: "13/9/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This document presents all the information that goes into the region cards. The idea is that is placed in the card, but if any ipdated are made to this file then the new version should be also updated in the corresponding section of region_card.Rnw

### What is the Ocean Health Index (OHI)?
The OHI is a scientific framework used to measure how healthy oceans are. Understanding the state of our oceans is a first step towards ensuring they can continue providing humans benefits now and in the future.

### Why is it important?
The ocean plays a critical role in supporting human well-being from providing food to regulating global climate. This index provides a powerful tool to raise public awareness, direct resource management, improve policy and prioritize scientific research. 

### How is it calculated?
The OHI combines many indicators into a comprehensive framework describing ocean health. An Index score for 220 countries and territories, the Antarctic region, is calculated every year, using best global data available.

### Goal definitions

*Artisanal Opportunity (AO)* Opportunity for small-scale fishers to supply catch to local communities or sell in local market.
*Biodiversity (BD)* Conservation status of marine species and key habitats, which inform about the rest of species that depend on them.
*Carbon Storage (CS)* Condition of coastal habitats that store and sequester atmospheric carbon.
*Clean Water (CW)* Degree to which oceans are free of chemicals contaminants, excessive nutrients, human pathogens and trash.
*Livelihoods and Economies (LE)* Coastal and ocean-dependent livelihoods (job quantity and quality) and economies (revenues) produced by marine sectors.
*Coastal Protection (CP)* The amount of protection provided by marine and coastal habitats serving as natural buffers against incoming.
*Food Provision (FP)* The sustainable harvest of seafood from wild-caught fisheries and mariculture.
*Natural Products (NP)* The natural resources that are sustainably extracted from living marine resources.
*Sense of Place (SP)* The conservation status of iconic species and geographic locations that contribute to cultural identity.
*Tourism and Recreation (TR)* The value people have for experiencing and enjoying coastal areas and attractions.





