---
title: "Plotting regions global scores over time"
author: "Camila Vargas"
date: "8/23/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Setup

```{r}
library(tidyverse)
library(plotly)
library(readr)
library(cowplot)
library(ggrepel)
library(RColorBrewer)


```

## Data wrangling

Prapare the data frame for plotting

```{r}

##Read in the socres
scores <- read.csv('https://raw.githubusercontent.com/OHI-Science/ohi-global/draft/eez/scores.csv') %>%
  rename(abb = "goal")


#Goals Description according to "short version" 
goals <-  data.frame(goal = c("Index", 
                              "Artisanal Opporunities", 
                              "Biodiversity",
                              "Carbon Storage",
                              "Clean Waters", 
                              "Livelihoods and Economies",
                              "Coastal Protection", 
                              "Food Provision",
                              "Natural Products", 
                              "Sense of Place", 
                              "Tourism and Recreation"), 
                     abb = c("Index", 
                             "AO", 
                             "BD", 
                             "CS",
                             "CW", 
                             "LE", 
                             "CP", 
                             "FP", 
                             "NP", 
                             "SP", 
                             "TR"), 
                     description = c("Overall Ocean Health Index score", 
                                     "Opportunity for small-scale fishers to supply <br> catch to their families, community or local market", 
                                     "Conservation status of native marine species and key habitats", 
                                     "Condition of coastal habitats that store and <br> sequester atmospheric carbon", 
                                     "Degree to which oceans are free of contaminants such as  <br> chemicals, excessive nutrients, human pathogens, and trash", 
                                     "Coastal and ocean-dependent livelihoods (job quantity and quality) <br> and economies (revenues) produced by marine sectors", 
                                     "Amount of protection provided by marine and coastal habitats <br> serving as natural buffers against incoming waves", 
                                     "Sustainable harvest of seafood from wild-caught <br> fisheries and mariculture ", 
                                     "Natural resources that are sustainably extracted <br> from living marine resources", 
                                     "Conservation status of iconic species and geographic <br> locations that contribute to cultural identity", 
                                     "Value people have for experiencing and enjoying <br> coastal areas and attractions")) 


## Add goal description to the data frame (important for plotly hover) and some more wranglinf --> filter information we need
scores_description <- scores %>% 
  left_join(goals, by= "abb") %>% 
  mutate(label = ifelse(year == max(year), as.character(abb), NA_character_)) %>% 
  dplyr::filter(dimension == 'score') %>% 
  dplyr::filter(abb %in% c('AO', 'BD', 'CP', 'CS', 'CW', 'FP', 'Index', 'LE', 'NP', 'SP', 'TR'))


```



## Test plot on one country
Writing steps of for loop to create figures for all countries

```{r}
## 1. Filter for the region - CHANGE CHILE FOR rgn_scores
chile <- scores_description %>% 
  dplyr::filter(region_id=='224') ## maybe ise i in the loop??

## 2. Plot

library(cowplot)
chile_plot <- ggplot(chile %>%
                         filter(abb != "Index"),
                       aes(x = year, y = score, color = goal)) +
  geom_line(data = chile %>% 
              filter( abb == "Index"),
            aes(x = year, y = score), size = 1.5, color = 'gray20', alpha = .9) +
  geom_point(data = chile %>% 
              filter( abb == "Index"),
            aes(x = year, y = score, text = paste("Goal: ", goal, "<br>Year:", year, "<br>Score:", score, "<br>Description: ", description)), size = 1.8, color = 'gray20', alpha = .9)+
  geom_text_repel(data= chile %>% 
                    filter( abb == "Index"),
                    aes(label = label), na.rm=TRUE, nudge_x= 0.1, point.padding = unit(8, "points"), nudge_y = 0, size= 2, segment.color=NA, color = 'gray20')+
  geom_line(aes(group = goal), alpha = .7, size = .8)+
  geom_point(aes(text = paste("Goal: ", goal, "<br>Year:", year, "<br>Score:", score, "<br>Description: ", description)), size = 1)+
    scale_x_continuous(breaks = seq(2012, 2018, 1))+
  labs(y="Score", color = "Goal")+ 
  theme_light()+
  theme(#axis.text.x = element_text(angle = 30),
        axis.title.x = element_blank(),
        legend.position = "None") +
  geom_text_repel(aes(label = label), na.rm=TRUE, nudge_x= 0.1, point.padding = unit(8, "points"), nudge_y = 0, size=2, segment.color=NA) +
  scale_color_viridis_d()+
  guides(colour = guide_legend(override.aes = list(size = 3)))

plot(chile_plot)





```




